NTBS-2944: Add notifying service and 12/24/36 month responsible clinic
publichealthengland/ntbs-reporting pull request #139
Opened 2021-12-21 09:53 UTC by LeoCie

I also fixed a bug where notifications with no diagnosis made/treatment start event were not having outcomes generated in reporting (this was happening with post mortem cases as some only have death events)

2021-12-21 09:53 UTC, LeoCie commented on source/dbo/Stored Procedures/Power BI Reporting/uspGenerateRecordOutcome.sql
> +			AND (te.TreatmentEventType = 'TreatmentStart' OR te.TreatmentEventType = 'DiagnosisMade')
This was the bug fix

2021-12-22 12:06 UTC, JoshCadney requested changes

2021-12-22 12:06 UTC, JoshCadney commented on source/dbo/Stored Procedures/Power BI Reporting/uspGenerateNtbsCaseRecord.sql
> +	SELECT * INTO #TempTransfers FROM firstTransferOut;
The "notifying" fields are really just "TB service responsible at 0 months" so I think we should calculate them all in the same file, and use similar logic for all

2021-12-22 14:45 UTC, LeoCie commented on source/dbo/Stored Procedures/Power BI Reporting/uspGenerateRecordOutcome.sql
> +	EXEC [dbo].[uspGenerateReusableOutcomePeriodic] 3;
I'm fairly surely it's actually needed here to terminate the exec statement before the "WITH".
Without it this happens:
![image](https://user-images.githubusercontent.com/78739678/147110144-96993a7a-517d-468c-af90-ec0a504317dd.png)

2021-12-22 14:54 UTC, JoshCadney commented on source/dbo/Stored Procedures/Power BI Reporting/uspGenerateRecordOutcome.sql
> +	EXEC [dbo].[uspGenerateReusableOutcomePeriodic] 3;
Very strange! In that case, could you add a semi colon to each of those exec statement, so it's less jarring to the eye!

2021-12-22 18:11 UTC, JoshCadney approved these changes
Looks good :-)

2021-12-22 18:11 UTC, merged