NTBS-2944: Fix service responsible fields in case data
publichealthengland/ntbs-reporting pull request #140
Opened 2022-01-05 18:00 UTC by LeoCie

Only generate a "service responsible at X months" if there is an outcome at X months (for 24 and 36, 12 is always calculated).
Brought the logic into it's own function.
Fixed the case where there is a transfer on the day of the outcome.

2022-01-06 09:00 UTC, aptemus reviewed
@LeoCie I've added some comments but let's see with @JoshCadney thinks.

2022-01-06 09:54 UTC, JoshCadney requested changes

2022-01-06 09:54 UTC, JoshCadney commented on source/dbo/Functions/Reusable Notification/ufnGetServiceResponsible.sql
> +	@TimePeriod int,
I think `NumberOfYears` would be better than `TimePeriod` as a name for this variable

2022-01-06 09:54 UTC, JoshCadney commented on source/dbo/Functions/Reusable Notification/ufnGetServiceResponsible.sql
> +			),
I don't think we need these two cases, I think it's equivalent to:
```
SELECT TOP 1 trans.TbServiceName
			FROM AllTransfers trans
			WHERE trans.NotificationId = @NotificationId
				AND trans.EventDate > DATEADD(DAY, -1, DATEADD(YEAR, @TimePeriod, @StartDate))
				AND trans.TransferType = 'TransferOut'
			ORDER BY EventDate
```
i.e. if there's a transfer on the day then the transfer in should match the transfer out of the next transfer (and if there isn't another transfer then it should match the current TB service)

2022-01-06 09:54 UTC, JoshCadney commented on source/dbo/Functions/Reusable Notification/ufnGetServiceResponsible.sql
> +			),
Having thought about it a little more, they won't be equivalent if the transfers on the record aren't consistent with the current TB service, but in that case I think it's better to prefer the current TB service anyway.

2022-01-06 09:54 UTC, JoshCadney commented on source/dbo/Stored Procedures/Power BI Reporting/uspGenerateRecordOutcome.sql
> +		COALESCE(
Yes, I suppose it's true that "notifying TB service" isn't always equivalent to "TB service responsible at 0 years" if the case is transferred after notification but before the treatment start date.

I agree that a subquery would be slightly better.

2022-01-07 12:29 UTC, JoshCadney reviewed
I think this looks good, but I also think we'll want to make changes following NTBS-2932 so that the notifying clinic/case manager are taken from the initial event, rather than using transfers (which are far less reliable).

So I think we should hold off on merging for now

2022-01-14 17:13 UTC, JoshCadney requested changes
Looks good, only a very minor improvement suggested

2022-01-14 17:13 UTC, JoshCadney commented on source/dbo/Stored Procedures/Power BI Reporting/uspGenerateRecordOutcome.sql
> +	(SELECT DISTINCT NotificationId,
I think the `DISTINCT` here adds a false sense of security - if the notification did somehow end up with more than one treatment start/diagnosis made event then it's also possible that those events would have different TB services. I think it's better not to have the `DISTINCT` call and maybe comment saying each notification will only have one such event.

2022-01-17 10:42 UTC, merged