NTBS-2259: Add default no result value for chest xray for all case record
publichealthengland/ntbs-reporting pull request #51
Opened 2021-05-14 15:33 UTC by LeoCie

Add the 'No result' value to ETS records chest xray result.

2021-05-14 15:47 UTC, aptemus approved these changes
@LeoCie looks good to me

2021-05-14 15:50 UTC, JoshCadney requested changes

2021-05-14 15:50 UTC, JoshCadney commented on source/dbo/Stored Procedures/Power BI Reporting/uspGenerateReportingCaseData.sql
> +		THEN 'No result' ELSE ChestXRayResult END
Why aren't we using `COALESCE` here?

2021-05-14 16:35 UTC, LeoCie commented on source/dbo/Stored Procedures/Power BI Reporting/uspGenerateReportingCaseData.sql
> +		THEN 'No result' ELSE ChestXRayResult END
Friday afternoon!

2021-05-17 07:49 UTC, JoshCadney approved these changes
Looks good :-)

2021-05-17 10:38 UTC, merged